# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1140, 597)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 693, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.tabsides = QtWidgets.QHBoxLayout()
        self.tabsides.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.tabsides.setObjectName("tabsides")
        self.tabBox = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBox.sizePolicy().hasHeightForWidth())
        self.tabBox.setSizePolicy(sizePolicy)
        self.tabBox.setMinimumSize(QtCore.QSize(300, 180))
        self.tabBox.setMaximumSize(QtCore.QSize(16777215, 180))
        self.tabBox.setObjectName("tabBox")
        self.userTab = QtWidgets.QWidget()
        self.userTab.setObjectName("userTab")
        self.layoutWidget = QtWidgets.QWidget(self.userTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.userName = QtWidgets.QLineEdit(self.layoutWidget)
        self.userName.setObjectName("userName")
        self.gridLayout_2.addWidget(self.userName, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.passwordIput = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordIput.setObjectName("passwordIput")
        self.gridLayout_2.addWidget(self.passwordIput, 1, 1, 1, 1)
        self.login = QtWidgets.QPushButton(self.layoutWidget)
        self.login.setObjectName("login")
        self.gridLayout_2.addWidget(self.login, 2, 1, 1, 1)
        self.userRegister = QtWidgets.QPushButton(self.layoutWidget)
        self.userRegister.setObjectName("userRegister")
        self.gridLayout_2.addWidget(self.userRegister, 3, 1, 1, 1)
        self.tabBox.addTab(self.userTab, "")
        self.portTab = QtWidgets.QWidget()
        self.portTab.setObjectName("portTab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.portTab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 312, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.openPort = QtWidgets.QPushButton(self.layoutWidget_2)
        self.openPort.setObjectName("openPort")
        self.gridLayout_3.addWidget(self.openPort, 0, 0, 1, 2)
        self.port = QtWidgets.QComboBox(self.layoutWidget_2)
        self.port.setObjectName("port")
        self.gridLayout_3.addWidget(self.port, 2, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.closePort = QtWidgets.QPushButton(self.layoutWidget_2)
        self.closePort.setObjectName("closePort")
        self.gridLayout_3.addWidget(self.closePort, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.baundrate = QtWidgets.QComboBox(self.layoutWidget_2)
        self.baundrate.setObjectName("baundrate")
        self.gridLayout_3.addWidget(self.baundrate, 1, 1, 1, 2)
        self.tabBox.addTab(self.portTab, "")
        self.pumpTab = QtWidgets.QWidget()
        self.pumpTab.setObjectName("pumpTab")
        self.layoutWidget_3 = QtWidgets.QWidget(self.pumpTab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(11, 10, 281, 121))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.openPlatform = QtWidgets.QPushButton(self.layoutWidget_3)
        self.openPlatform.setObjectName("openPlatform")
        self.gridLayout_5.addWidget(self.openPlatform, 0, 0, 1, 1)
        self.closePlatform = QtWidgets.QPushButton(self.layoutWidget_3)
        self.closePlatform.setObjectName("closePlatform")
        self.gridLayout_5.addWidget(self.closePlatform, 1, 0, 1, 1)
        self.setCurrent = QtWidgets.QPushButton(self.layoutWidget_3)
        self.setCurrent.setObjectName("setCurrent")
        self.gridLayout_5.addWidget(self.setCurrent, 1, 1, 1, 2)
        self.currentSpin = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.currentSpin.setMaximum(10000)
        self.currentSpin.setSingleStep(50)
        self.currentSpin.setObjectName("currentSpin")
        self.gridLayout_5.addWidget(self.currentSpin, 0, 2, 1, 1)
        self.tabBox.addTab(self.pumpTab, "")
        self.logTab = QtWidgets.QWidget()
        self.logTab.setObjectName("logTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.logTab)
        self.horizontalLayout.setContentsMargins(15, 15, 15, 15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.historyGridLayout = QtWidgets.QGridLayout()
        self.historyGridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.historyGridLayout.setObjectName("historyGridLayout")
        self.logButton = QtWidgets.QPushButton(self.logTab)
        self.logButton.setObjectName("logButton")
        self.historyGridLayout.addWidget(self.logButton, 2, 1, 1, 1)
        self.stepEdit = QtWidgets.QSpinBox(self.logTab)
        self.stepEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stepEdit.setMaximum(10000)
        self.stepEdit.setProperty("value", 1)
        self.stepEdit.setObjectName("stepEdit")
        self.historyGridLayout.addWidget(self.stepEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.logTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.historyGridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.logTab)
        self.label_8.setObjectName("label_8")
        self.historyGridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.timeEdit = QtWidgets.QDateTimeEdit(self.logTab)
        self.timeEdit.setObjectName("timeEdit")
        self.historyGridLayout.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.ticker = QtWidgets.QLCDNumber(self.logTab)
        self.ticker.setEnabled(False)
        self.ticker.setObjectName("ticker")
        self.historyGridLayout.addWidget(self.ticker, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.historyGridLayout)
        self.logGridLayout = QtWidgets.QGridLayout()
        self.logGridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.logGridLayout.setObjectName("logGridLayout")
        self.historyEdit = QtWidgets.QPlainTextEdit(self.logTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyEdit.sizePolicy().hasHeightForWidth())
        self.historyEdit.setSizePolicy(sizePolicy)
        self.historyEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.historyEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.historyEdit.setObjectName("historyEdit")
        self.logGridLayout.addWidget(self.historyEdit, 1, 0, 1, 3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.printButton = QtWidgets.QPushButton(self.logTab)
        self.printButton.setMinimumSize(QtCore.QSize(100, 0))
        self.printButton.setObjectName("printButton")
        self.verticalLayout.addWidget(self.printButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.logGridLayout.addLayout(self.verticalLayout, 1, 3, 1, 1)
        self.horizontalLayout.addLayout(self.logGridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tabBox.addTab(self.logTab, "")
        self.tabsides.addWidget(self.tabBox)
        self.mainLayout.addLayout(self.tabsides)

        self.retranslateUi(Form)
        self.tabBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "密码："))
        self.login.setText(_translate("Form", "登录"))
        self.userRegister.setText(_translate("Form", "注册"))
        self.tabBox.setTabText(self.tabBox.indexOf(self.userTab), _translate("Form", "用户登录"))
        self.openPort.setText(_translate("Form", "打开串口"))
        self.label_6.setText(_translate("Form", "串口号："))
        self.closePort.setText(_translate("Form", "关闭串口"))
        self.label_5.setText(_translate("Form", "波特率："))
        self.tabBox.setTabText(self.tabBox.indexOf(self.portTab), _translate("Form", "串口设置"))
        self.label_7.setText(_translate("Form", " 电流："))
        self.openPlatform.setText(_translate("Form", "打开平台"))
        self.closePlatform.setText(_translate("Form", "关闭平台"))
        self.setCurrent.setText(_translate("Form", "设置"))
        self.currentSpin.setSuffix(_translate("Form", "mA"))
        self.tabBox.setTabText(self.tabBox.indexOf(self.pumpTab), _translate("Form", "泵浦开关"))
        self.logButton.setText(_translate("Form", "开始"))
        self.stepEdit.setSuffix(_translate("Form", "秒"))
        self.label_3.setText(_translate("Form", "记录时长："))
        self.label_8.setText(_translate("Form", "记录步长："))
        self.printButton.setText(_translate("Form", "    打印    "))
        self.tabBox.setTabText(self.tabBox.indexOf(self.logTab), _translate("Form", "功率计"))

